/* Generated By:JavaCC: Do not edit this line. UnitParserConstants.java */
package visad.data.netcdf.units;

public interface UnitParserConstants {

  int EOF = 0;
  int SIGN = 7;
  int DIGIT = 8;
  int INT = 9;
  int INTEGER = 10;
  int EXP = 11;
  int DECIMAL = 12;
  int REAL = 13;
  int SINCE = 14;
  int FROM = 15;
  int SHIFT = 16;
  int DIVIDE = 17;
  int LETTER = 18;
  int NAME = 19;
  int YEAR = 20;
  int MONTH = 21;
  int DAY = 22;
  int DATE = 23;
  int HOUR = 24;
  int MINUTE = 25;
  int SECOND = 26;
  int TIME = 27;
  int UTC = 28;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"*\"",
    "\".\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SIGN>",
    "<DIGIT>",
    "<INT>",
    "<INTEGER>",
    "<EXP>",
    "<DECIMAL>",
    "<REAL>",
    "<SINCE>",
    "<FROM>",
    "<SHIFT>",
    "<DIVIDE>",
    "<LETTER>",
    "<NAME>",
    "<YEAR>",
    "<MONTH>",
    "<DAY>",
    "<DATE>",
    "<HOUR>",
    "<MINUTE>",
    "<SECOND>",
    "<TIME>",
    "<UTC>",
    "\";\"",
    "\"\\u0000\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
  };

}
