/* Generated by Together */

package visad.data.in;

import java.rmi.RemoteException;
import visad.*;

abstract public class DoubleRange
    extends RealRange
{
    protected DoubleRange(RealType type, int length)
    {
	super(type, length);
    }

    public void set(Field field)
	throws VisADException, RemoteException
    {
	field.setSamples(getDoubles());
    }

    public float[][] getFloats()
    {
	double[][]	inArray = getDoubles();
	float[][]	outArray = new float[inArray.length][];
	for (int i = 0; i < inArray.length; ++i)
	{
	    double[]	inVec = inArray[i];
	    float[]	outVec = new float[inVec.length];
	    for (int j = 0; j < outVec.length; ++j)
		outVec[j] = (float)inVec[j];
	    outArray[i] = outVec;
	}
	return outArray;
    }

    abstract public double[][] getDoubles();
}
