/* Generated by Together */

package visad.data.in;

import visad.*;

/**
 * Instances are immutable.
 */
abstract public class ScalarRange
    extends Range
{
    private MathType	mathType;

    protected ScalarRange(MathType type, int length)
    {
	super(length);
	this.mathType = mathType;
    }

    public MathType getMathType()
    {
	return mathType;
    }

    public ScalarType getScalarType()
    {
	return (ScalarType)getMathType();
    }

    public Object clone()
    {
	return this;	// because instances are immutable
    }
}
