/* Generated by Together */

package visad.data.in;

import java.rmi.RemoteException;
import visad.*;

public class TimeFactorer
    extends DataFilter
{
    public TimeFactorer(DataSink downstream)
    {
	super(downstream);
    }

    public void receive(Field field)
	throws VisADException, RemoteException
    {
	RealTupleType	domainType =
	    ((FunctionType)field.getType()).getDomain();
	int		dimensionCount = domainType.getDimension();
	if (dimensionCount > 1)
	{
	    RealType	outerDimensionType = (RealType)
		domainType.getComponent(dimensionCount - 1);
	    if ((RealType.Time.equalsExceptNameButUnits(outerDimensionType) ||
		  RealType.TimeInterval.equalsExceptNameButUnits(
		    outerDimensionType)) &&
		 field.getDomainSet() instanceof ProductSet)
	    {
		field = field.domainFactor(outerDimensionType);
	    }
	}
	send(field);
    }
}
