/* Generated by Together */

package visad.data.in;

import visad.*;

public abstract class VirtualScalar
    extends VirtualData
{
    public static String scalarName(String name)
    {
	return name
	    .replace('.', '-')
	    .replace(' ', '_')
	    .replace('(', '<')
	    .replace(')', '>');
    }
}
