/* Generated by Together */

package visad.data.in;

import java.util.*;
import java.rmi.RemoteException;
import visad.*;

/**
 * Instances are mutable.
 */
abstract public class VirtualData
{
    public abstract MathType getMathType();

    /**
     * Doesn't clone components.
     * Override in mutable subclasses.
     */
    public List getComponents()
    {
	ArrayList	list = new ArrayList(1);
	list.add(this);
	return list;
    }

    /**
     * Default method.
     */
    public Object getMergeKey()
    {
	return null;
    }

    /**
     */
    public void add(VirtualData data)
	throws NotMergeableException, VisADException
    {
	throw new NotMergeableException(
	    getClass().getName() + ".add(VirtualData): " +
	    "This object is immutable and can't be added to");
    }

    /**
     * Returns the VisAD data object corresponding to this virtual data object.
     */
    public abstract Data getData()
	throws VisADException, RemoteException;
}
