/* Generated by Together */

package visad.data.in;

import visad.VisADException;

public interface VirtualDataSink
{
    void receive(VirtualReal real)
	throws VisADException;

    void receive(VirtualText text)
	throws VisADException;

    void receive(VirtualScalar scalar)
	throws VisADException;

    void receive(VirtualSet set)
	throws VisADException;

    void receive(VirtualField field)
	throws VisADException;

    void receive(VirtualTuple tuple)
	throws VisADException;

    void receive(VirtualData data)
	throws VisADException;

    void flush()
	throws VisADException;
}
