/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class visad_data_hdfeos_hdfeosNative_hdfeosLib */

#ifndef _Included_visad_data_hdfeos_hdfeosNative_hdfeosLib
#define _Included_visad_data_hdfeos_hdfeosNative_hdfeosLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    EHclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_EHclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    EHchkfid
 * Signature: (ILjava/lang/String;[I[I[B)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_EHchkfid
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jbyteArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDinqattrs
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDinqattrs
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDprojinfo
 * Signature: (I[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDprojinfo
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDgridinfo
 * Signature: (I[I[I[D[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDgridinfo
  (JNIEnv *, jobject, jint, jintArray, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWinqswath
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWinqswath
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDinqgrid
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDinqgrid
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWinqdims
 * Signature: (II[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWinqdims
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDinqdims
 * Signature: (II[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDinqdims
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWopen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDopen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWattach
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWattach
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDattach
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDattach
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWinqdatafields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWinqdatafields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWinqgeofields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWinqgeofields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDinqfields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDinqfields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWinqmaps
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWinqmaps
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWnentries
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWnentries
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDnentries
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDnentries
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWfieldinfo
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWfieldinfo
  (JNIEnv *, jobject, jint, jstring, jint, jobjectArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDfieldinfo
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDfieldinfo
  (JNIEnv *, jobject, jint, jstring, jint, jobjectArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWfdims
 * Signature: (ILjava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWfdims
  (JNIEnv *, jobject, jint, jstring, jstring, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    GDfdims
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_GDfdims
  (JNIEnv *, jobject, jint, jstring, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[F)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3F
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jfloatArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3D
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3I
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosNative_hdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[S)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosNative_hdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3S
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
