/* Generated by Together */

package visad.data.in;

import java.rmi.RemoteException;
import visad.*;

abstract public class AbstractDataSink
    implements DataSink
{
    public void receive(Real real)
	throws VisADException, RemoteException
    {
	receive((Scalar)real);
    }

    public void receive(Text text)
	throws VisADException, RemoteException
    {
	receive((Scalar)text);
    }

    public void receive(Scalar scalar)
	throws VisADException, RemoteException
    {
	receive((DataImpl)scalar);
    }

    public void receive(Set set)
	throws VisADException, RemoteException
    {
	receive((DataImpl)set);
    }

    public void receive(Field field)
	throws VisADException, RemoteException
    {
	receive((DataImpl)field);
    }

    public void receive(Tuple tuple)
	throws VisADException, RemoteException
    {
	receive((DataImpl)tuple);
    }
}
