/* Generated by Together */

package visad.data.in;

import visad.VisADException;

abstract public class AbstractVirtualDataSink
    implements VirtualDataSink
{
    public void receive(VirtualReal real)
	throws VisADException
    {
	receive((VirtualScalar)real);
    }

    public void receive(VirtualText text)
	throws VisADException
    {
	receive((VirtualScalar)text);
    }

    public void receive(VirtualScalar scalar)
	throws VisADException
    {
	receive((VirtualData)scalar);
    }

    public void receive(VirtualSet set)
	throws VisADException
    {
	receive((VirtualData)set);
    }

    public void receive(VirtualField field)
	throws VisADException
    {
	receive((VirtualData)field);
    }

    public void receive(VirtualTuple tuple)
	throws VisADException
    {
	receive((VirtualData)tuple);
    }
}
