/* Generated by Together */

package visad.data.in;

import java.rmi.RemoteException;
import visad.*;

abstract public class FloatRange
    extends RealRange
{
    protected FloatRange(RealType type, int length)
    {
	super(type, length);
    }

    public void set(Field field)
	throws VisADException, RemoteException
    {
	field.setSamples(getFloats());
    }

    public abstract float[][] getFloats();

    public double[][] getDoubles()
    {
	float[][]	inArray = getFloats();
	double[][]	outArray = new double[inArray.length][];
	for (int i = 0; i < inArray.length; ++i)
	{
	    float[]	inVec = inArray[i];
	    double[]	outVec = new double[inVec.length];
	    for (int j = 0; j < outVec.length; ++j)
		outVec[j] = (double)inVec[j];
	    outArray[i] = outVec;
	}
	return outArray;
    }
}
