/* Generated by Together */

package visad.data.in;

import visad.*;

public class Selector extends VirtualDataFilter 
    
{
    private MathType	targetType;

    public Selector(VirtualDataSink downstream)
    {
	super(downstream);
    }

    /**
     * @param targetType	The {@link MathType} to pass.  May be
     *				<code>null</code> -- in which case everything is
     *				passed.
     */
    public void setMathType(MathType targetType)
    {
	this.targetType = targetType;
    }

    public void receive(VirtualData data)
	throws VisADException
    {
        if (data.getMathType().equals(targetType))
	    send(data);
    }
}
