/* Generated by Together */

package visad.data.in;

import java.rmi.RemoteException;
import visad.*;

public class Selector extends DataFilter
    
{
    private MathType	targetType;

    public Selector(DataSink downstream)
    {
	super(downstream);
    }

    /**
     * @param targetType	The {@link MathType} to pass.  May be
     *				<code>null</code> -- in which case everything is
     *				passed.
     */
    public void setMathType(MathType targetType)
    {
	this.targetType = targetType;
    }

    public void receive(DataImpl data)
	throws VisADException, RemoteException
    {
        if (data.getType().equals(targetType))
	    send(data);
    }
}
