/* Generated by Together */

package visad.data.in;

import visad.*;

public class VirtualText
    extends VirtualScalar
{
    private final Text	text;

    protected VirtualText(TextType textType, String value)
	throws VisADException
    {
	text = new Text(textType, value);
    }

    /**
     * The name is modified as necessary to conform to VisAD standards.
     */
    public static VirtualText instance(String name, String value)
	throws VisADException
    {
	return instance(TextType.getTextType(scalarName(name)), value);
    }

    /**
     */
    public static VirtualText instance(TextType textType, String value)
	throws VisADException
    {
	return new VirtualText(textType, value);
    }

    public MathType getMathType()
    {
	return text.getType();
    }

    public TextType getTextType()
    {
	return (TextType)getMathType();
    }

    public Text getText()
    {
	return text;
    }

    public Data getData()
    {
	return getText();
    }
}
