SUBPACKAGE	= 

include macros.make

GARBAGE		= plain.nc
SUBDIR_TARGETS	= units/default units/classes units/all units/clean

default:	units/default
all:		units/all
classes:	units/classes
clean:		units/clean

include rules.make

test:		Plain.test
