/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class visad_benjamin_Galaxy */

#ifndef _Included_visad_benjamin_Galaxy
#define _Included_visad_benjamin_Galaxy
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: NxpxMAX */
/* Inaccessible static: NypxMAX */
/* Inaccessible static: NRMAX */
/* Inaccessible static: NZMAX */
/* Inaccessible static: NXP */
/* Inaccessible static: NYP */
/* Inaccessible static: NZP */
/* Inaccessible static: NX */
/* Inaccessible static: NY */
/* Inaccessible static: NZ */
/* Inaccessible static: llast */
/* Inaccessible static: elast */
#undef visad_benjamin_Galaxy_F1
#define visad_benjamin_Galaxy_F1 0.36D
#undef visad_benjamin_Galaxy_F2
#define visad_benjamin_Galaxy_F2 40.0D
#undef visad_benjamin_Galaxy_Fa
#define visad_benjamin_Galaxy_Fa 6.0D
/*
 * Class:     visad_benjamin_Galaxy
 * Method:    getcon_c
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_visad_benjamin_Galaxy_getcon_1c
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     visad_benjamin_Galaxy
 * Method:    ismgsc_c
 * Signature: ([F[I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_visad_benjamin_Galaxy_ismgsc_1c
  (JNIEnv *, jobject, jfloatArray, jintArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
