/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class visad_data_hdfeos_hdfeosc_HdfeosLib */

#ifndef _Included_visad_data_hdfeos_hdfeosc_HdfeosLib
#define _Included_visad_data_hdfeos_hdfeosc_HdfeosLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    EHchkfid
 * Signature: (ILjava/lang/String;[I[I[B)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_EHchkfid
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jbyteArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    EHclose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_EHclose
  (JNIEnv *, jobject, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDattach
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDattach
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDfdims
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDfdims
  (JNIEnv *, jobject, jint, jstring, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDfieldinfo
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDfieldinfo
  (JNIEnv *, jobject, jint, jstring, jint, jobjectArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDgridinfo
 * Signature: (I[I[I[D[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDgridinfo
  (JNIEnv *, jobject, jint, jintArray, jintArray, jdoubleArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDinqattrs
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDinqattrs
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDinqdims
 * Signature: (II[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDinqdims
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDinqfields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDinqfields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDinqgrid
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDinqgrid
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDnentries
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDnentries
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDopen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    GDprojinfo
 * Signature: (I[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_GDprojinfo
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWattach
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWattach
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWfdims
 * Signature: (ILjava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWfdims
  (JNIEnv *, jobject, jint, jstring, jstring, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWfieldinfo
 * Signature: (ILjava/lang/String;I[Ljava/lang/String;[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWfieldinfo
  (JNIEnv *, jobject, jint, jstring, jint, jobjectArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWinqdatafields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWinqdatafields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWinqdims
 * Signature: (II[Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWinqdims
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWinqgeofields
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWinqgeofields
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWinqmaps
 * Signature: (II[Ljava/lang/String;[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWinqmaps
  (JNIEnv *, jobject, jint, jint, jobjectArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWinqswath
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWinqswath
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWnentries
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWnentries
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWopen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWopen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[D)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3D
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jdoubleArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[F)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3F
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jfloatArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3I
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jintArray);

/*
 * Class:     visad_data_hdfeos_hdfeosc_HdfeosLib
 * Method:    SWreadfield
 * Signature: (ILjava/lang/String;[I[I[I[S)I
 */
JNIEXPORT jint JNICALL Java_visad_data_hdfeos_hdfeosc_HdfeosLib_SWreadfield__ILjava_lang_String_2_3I_3I_3I_3S
  (JNIEnv *, jobject, jint, jstring, jintArray, jintArray, jintArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
